version: '3'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
     - .:/server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: django
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django
  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    command: sh -c " python3 manage.py runserver 0.0.0.0:8000 && nohup uwsgi --socket :8001 --module core.wsgi & daphne -b 0.0.0.0 -p 3001 --ping-interval 10 --ping-timeout 120 core.asgi:application && python3 manage.py makemigrations && python3 manage.py migrate"
    volumes:
     - ./django:/server
    ports:
     - "8080:8000"
    depends_on:
     - db
     - redis
  redis:
    image: redis:alpine
    expose:
      - "6379"

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    command: 'sh /etc/nginx/start-nginx.sh'
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - 8000:8000
    volumes:
      - ./nginx/logs/nginx/:/var/log/nginx/
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./django/static:/var/www/static/
    depends_on:
      - django
