# Generated by Django 2.2.6 on 2019-11-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji_name', models.CharField(max_length=10, verbose_name='名前（漢字）')),
                ('hiragana_name', models.CharField(max_length=30, verbose_name='名前（ひらがな）')),
                ('distance', models.IntegerField(choices=[(1, '50m'), (2, '100m'), (3, '200m'), (4, '400m'), (5, '800m'), (6, '1500m')], default=1, verbose_name='距離')),
                ('event', models.IntegerField(choices=[(1, '自由形'), (2, '背泳ぎ'), (3, '平泳ぎ'), (4, 'バタフライ'), (5, '個人メドレー')], default=1, verbose_name='種目')),
                ('time_min', models.IntegerField(default=0, verbose_name='分')),
                ('time_sec', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='備考')),
            ],
        ),
    ]
